// Mocks generated by Mockito 5.4.6 from annotations
// in im_mottu_mobile/test/mocks/pokemon_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:im_mottu_mobile/app/shared/interfaces/i_pokemon_service.dart'
    as _i2;
import 'package:im_mottu_mobile/app/shared/models/pokemon_details_model.dart'
    as _i6;
import 'package:im_mottu_mobile/app/shared/models/pokemon_model.dart' as _i4;
import 'package:im_mottu_mobile/app/shared/repositories/pokemon_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIPokemonService_0 extends _i1.SmartFake
    implements _i2.IPokemonService {
  _FakeIPokemonService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i3.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IPokemonService get service =>
      (super.noSuchMethod(
            Invocation.getter(#service),
            returnValue: _FakeIPokemonService_0(
              this,
              Invocation.getter(#service),
            ),
          )
          as _i2.IPokemonService);

  @override
  List<_i4.PokemonModel> get cachedList =>
      (super.noSuchMethod(
            Invocation.getter(#cachedList),
            returnValue: <_i4.PokemonModel>[],
          )
          as List<_i4.PokemonModel>);

  @override
  set cachedList(List<_i4.PokemonModel>? _cachedList) => super.noSuchMethod(
    Invocation.setter(#cachedList, _cachedList),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i4.PokemonModel>> getPokemons() =>
      (super.noSuchMethod(
            Invocation.method(#getPokemons, []),
            returnValue: _i5.Future<List<_i4.PokemonModel>>.value(
              <_i4.PokemonModel>[],
            ),
          )
          as _i5.Future<List<_i4.PokemonModel>>);

  @override
  _i5.Future<_i6.PokemonDetailsModel?> getPokemonDetails(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemonDetails, [index]),
            returnValue: _i5.Future<_i6.PokemonDetailsModel?>.value(),
          )
          as _i5.Future<_i6.PokemonDetailsModel?>);

  @override
  _i5.Future<List<_i4.PokemonModel>> getPokemonsByType(String? type) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemonsByType, [type]),
            returnValue: _i5.Future<List<_i4.PokemonModel>>.value(
              <_i4.PokemonModel>[],
            ),
          )
          as _i5.Future<List<_i4.PokemonModel>>);

  @override
  _i5.Future<List<_i4.PokemonModel>> getPokemonsByAbility(String? ability) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemonsByAbility, [ability]),
            returnValue: _i5.Future<List<_i4.PokemonModel>>.value(
              <_i4.PokemonModel>[],
            ),
          )
          as _i5.Future<List<_i4.PokemonModel>>);
}
